name: Run Python Script

on:
  schedule:
    - cron: '0 22 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python "first step BS pe.py"
      - name: Upload PE-filtered stocks
        uses: actions/upload-artifact@v4
        with:
          name: pe-filtered-stocks
          path: A股低市盈率股票.xlsx
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: stock-data
        path: stock_data.xlsx
